remote_theme: chesterhow/tale

# Site settings
title:          anti.science
description:    "None"
baseurl:        ""
url:            "https://anti.science"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         
  url:          
  email:        
# Build settings
markdown:       kramdown
include:
  - _pages


# Permalinks
permalink:      /:title
paginate:       5

